### ISSUE TITLE
incl. moet exc. zijn

### ISSUE THREAD

**Issue by sw53891** [thijsotter/woocommerce-statiegeld#1]
Hallo,

Ik heb de plugin geinstalleerd en getest.
Er staat  dat de prijs incl. statiegeld is. Echter bij het afrekenen wordt het totale statiegeld er nogmaals bovenop berekend.
Dus de tekst zou 'excl. statiegeld' moeten zijn. En de prijzen dus ook exclusief statiegeld invoeren.
Verder ben ik blij met de plugin.

met vriendelijke groet,
Erwin

**Comment by thijsotter** [comment]
Beste Erwin,

Bedankt voor de melding. De plugin is aangepast. Er wordt nu weergeven excl. statiegeld.

Groet,
Thijs
